-- =============================================================
-- KanPassIt — Question Bank Expansion Batch 2
-- Subjects: NCLEX CNA (+70) and NCLEX RN (+70)
-- Combined with batch 1, each subject reaches 100 questions.
-- Domain targets:
--   CNA: ADL 29q · Basic Nursing 35q · Psychosocial 10q · Role 26q
--   RN:  Safe & Effective 32q · Physiological 51q · Health Promotion 9q · Psychosocial 9q
-- Clinical values verified: insulin peak times (LevelUpRN/ATI), lithium range (StatPearls/NCSBN)
-- =============================================================

-- ─────────────────────────────────────────────────────────────
-- NCLEX CNA  +70 questions  (subject_slug = 'cna')
-- ─────────────────────────────────────────────────────────────

INSERT INTO questions (subject_slug, domain, question_text, options, correct_index, explanation, active) VALUES

-- ── Activities of Daily Living  +20 ──────────────────────────

('cna','Activities of Daily Living',
 'When giving a bed bath, which area of the body should the nurse aide wash last?',
 '["Perineal area and buttocks", "Arms and hands", "Chest and abdomen", "Face and neck"]',
 0,
 'The perineal area and buttocks are washed last because they carry the highest bacterial load. Washing this area last prevents contaminating cleaner body areas. A fresh washcloth and water should always be used for this step.',
 true),

('cna','Activities of Daily Living',
 'A resident has dentures. When cleaning them, the nurse aide should:',
 '["Clean them with regular toothpaste and a hard-bristle toothbrush", "Soak them in boiling water to sterilize", "Hold them over a sink lined with a towel or filled with water, and brush with denture cleaner", "Leave them soaking in water indefinitely when not in use"]',
 2,
 'Dentures are fragile and expensive. The sink is padded or filled with water so they won''t shatter if dropped. Boiling water warps dentures. Regular toothpaste is too abrasive. Prolonged soaking can warp the material — they should be stored in fresh water or denture solution when not worn.',
 true),

('cna','Activities of Daily Living',
 'A resident is on bed rest and has not had a bowel movement in four days. What is the most important action for the nurse aide?',
 '["Ignore the situation because constipation is normal in older adults", "Offer the resident a laxative from the supply closet", "Report the finding to the nurse promptly", "Increase the resident''s fluid intake without notifying the nurse"]',
 2,
 'Four days without a bowel movement is a reportable change. The nurse must be notified to assess for constipation, fecal impaction, or other causes and to order appropriate interventions. The aide cannot independently administer medications or alter the care plan.',
 true),

('cna','Activities of Daily Living',
 'When assisting a resident to use a bedpan, what position should the resident be placed in if there are no restrictions?',
 '["Prone position", "Lying on the left side", "Head of bed elevated 30–45 degrees with the resident in a semi-sitting position", "Flat on the back with legs extended"]',
 2,
 'The semi-sitting position (head of bed elevated 30–45 degrees) mimics a natural sitting posture for elimination, uses gravity to aid evacuation, and reduces straining. Lying flat makes elimination difficult and increases the risk of aspiration.',
 true),

('cna','Activities of Daily Living',
 'Which action by the nurse aide best promotes good foot care for a diabetic resident?',
 '["Soak feet in hot water for 20 minutes daily", "Wash and dry feet thoroughly, including between the toes, and inspect for any breaks in skin", "Apply lotion between the toes to prevent dryness", "Cut corns and calluses to improve comfort"]',
 1,
 'Diabetic residents are at risk for peripheral neuropathy and impaired circulation, making foot wounds dangerous. Thorough washing, drying (especially between toes — moisture causes maceration), and inspection are correct. Cutting corns/calluses and applying lotion between toes can cause injury or fungal infection. Hot water soaks can cause burns due to decreased sensation.',
 true),

('cna','Activities of Daily Living',
 'A resident wears glasses. Which statement about eyeglass care is correct?',
 '["Leave glasses on the bedside table face-down to protect the lenses", "Clean lenses with a soft, clean cloth; store them in a case when not in use", "Rinse glasses under hot water to remove smudges", "Use paper towels to dry lenses after cleaning"]',
 1,
 'Soft cloths (microfiber or designated lens cloths) clean without scratching. Hot water can damage lens coatings. Paper towels are abrasive and scratch lenses. Placing glasses face-down scratches the lenses. Glasses should always be stored in a protective case.',
 true),

('cna','Activities of Daily Living',
 'A resident uses a hearing aid. When the resident reports the hearing aid is not working, the nurse aide should first:',
 '["Send the hearing aid to maintenance immediately", "Tell the resident to speak louder", "Assume the hearing aid is broken and remove it permanently", "Check if the battery is dead and replace it if necessary"]',
 3,
 'The most common cause of hearing aid malfunction is a dead battery. The aide should first check and replace the battery. If the problem persists after battery replacement, report to the nurse for further assessment or referral to an audiologist.',
 true),

('cna','Activities of Daily Living',
 'When performing a shampoo for a bedridden resident, the nurse aide should:',
 '["Skip conditioning because it takes too long", "Vigorously rub the scalp with fingernails to remove buildup", "Use hot water to stimulate the scalp", "Protect the resident''s eyes and ears from water and shampoo"]',
 3,
 'Water or shampoo in the eyes causes irritation; water in the ears can cause infection or discomfort. The aide should use warm (not hot) water, gentle fingertip massage (not nails), and follow facility protocol for conditioning.',
 true),

('cna','Activities of Daily Living',
 'A resident who is partially dependent needs help with meals. The nurse aide should:',
 '["Feed the entire meal to save time", "Remove the tray after 5 minutes if the resident eats slowly", "Encourage the resident to do as much self-feeding as possible and assist only when needed", "Stand over the resident and wait impatiently"]',
 2,
 'Encouraging maximum self-participation preserves the resident''s functional ability, independence, and dignity. Aides should set up trays, open containers, and cut food, but allow the resident to self-feed as much as safely possible. Adequate time must be given.',
 true),

('cna','Activities of Daily Living',
 'Which action promotes comfort and prevents complications when positioning a resident for sleep?',
 '["Elevate the head of the bed to 90 degrees for all residents", "Tuck sheets and blankets very tightly around the resident", "Place the resident in the same position every night", "Use pillows to support body alignment and prevent pressure on bony prominences"]',
 3,
 'Proper alignment with pillow support prevents pressure injuries, contractures, and musculoskeletal strain. One position every night causes pressure injuries. 90-degree elevation is only appropriate for specific conditions. Tight tucking restricts circulation and movement.',
 true),

('cna','Activities of Daily Living',
 'A nurse aide notices a resident''s nail is jagged and catching on bedding. What should the aide do?',
 '["File the nail smooth with an emery board and report the finding to the nurse", "Ignore it as nail care is not part of the aide''s duties", "Apply tape over the nail", "Cut the nail immediately with nail clippers"]',
 0,
 'Nurse aides can file fingernails smooth to prevent injury. Cutting nails (especially toenails) typically requires nurse assessment or a podiatrist order, particularly for diabetic or anticoagulated residents. Any skin concern should be reported.',
 true),

('cna','Activities of Daily Living',
 'When assisting a resident with a urinal, the nurse aide should:',
 '["Provide privacy, position the urinal correctly, and empty and rinse it after use", "Share urinals between residents to save supplies", "Empty the urinal at the end of the shift only", "Leave the urinal at the bedside without emptying it for staff convenience"]',
 0,
 'Privacy is a resident right. Urinals should be emptied promptly after each use, rinsed, and returned to an accessible place. Never sharing urinals prevents cross-contamination. Delayed emptying causes odor and bacterial growth.',
 true),

('cna','Activities of Daily Living',
 'A resident reports pain when being repositioned. The nurse aide''s best response is to:',
 '["Continue repositioning quickly to finish as fast as possible", "Tell the resident that some discomfort is normal and proceed", "Administer pain medication before the next repositioning", "Stop the repositioning, ask the nurse for guidance, and document the report"]',
 3,
 'Pain during repositioning may indicate injury, worsening condition, or inadequate pain control. The aide must stop, report to the nurse, and document. Continuing causes harm. Aides cannot administer medications independently.',
 true),

('cna','Activities of Daily Living',
 'A resident with limited mobility is being turned to the side. The nurse aide should:',
 '["Use a drawsheet and ask for help if the resident is heavy or has limited mobility", "Turn the resident quickly to minimize their discomfort", "Perform the turn alone regardless of the resident''s size", "Pull the resident by the arm to turn them"]',
 0,
 'Drawsheets reduce friction and distribute body weight, protecting both resident skin and aide back. Pulling on extremities can dislocate joints. Assistance prevents injury to both parties. Quick turns increase discomfort and injury risk.',
 true),

('cna','Activities of Daily Living',
 'When changing bed linens with a resident still in the bed, the nurse aide should:',
 '["Shake the soiled linens to loosen debris before removing", "Stack soiled linens on the chair while making the other side", "Fan soiled linens through the air to air them out", "Change one side at a time, rolling soiled linen away from the body before removing it"]',
 3,
 'Changing one side at a time (log roll technique) keeps the resident comfortable and safe. Rolling soiled linen toward the center contains any pathogens or body fluids. Shaking or airing soiled linens spreads microorganisms throughout the room.',
 true),

('cna','Activities of Daily Living',
 'A resident has a prescribed thickened-liquid diet. The nurse aide should:',
 '["Thin the liquids slightly if the resident requests it", "Offer only liquids at the prescribed consistency and report if the resident refuses or requests thin liquids", "Provide thickened liquids only at mealtimes and thin liquids at other times", "Give thin water between meals since it is not really a liquid"]',
 1,
 'Thickened liquids are prescribed to prevent aspiration in residents with dysphagia. The aide must follow the prescription exactly. Modifications require a nurse or speech therapist order. Thin water or unapproved liquids at any time can cause aspiration pneumonia.',
 true),

('cna','Activities of Daily Living',
 'Which method is safest when applying lotion to a resident''s back?',
 '["Warm the lotion in your hands first, then apply with long, smooth strokes in the direction of venous return", "Rub vigorously in circular motions to stimulate circulation", "Pour cold lotion directly onto the skin", "Apply lotion only if the skin appears dry and cracked"]',
 0,
 'Warming lotion prevents startling the resident and improves absorption. Long strokes toward the heart follow the direction of venous return, promoting circulation. Vigorous rubbing can damage fragile skin. Preventive lotion application is appropriate before skin breakdown occurs.',
 true),

('cna','Activities of Daily Living',
 'A resident with a Foley catheter needs to be ambulated. The nurse aide should:',
 '["Carry the drainage bag above the resident''s waist level for easy access", "Disconnect the catheter from the drainage bag during short walks", "Clamp the catheter tubing before ambulation to prevent leakage", "Keep the drainage bag below the level of the bladder at all times during ambulation"]',
 3,
 'Keeping the drainage bag below the bladder prevents urine from backflowing into the bladder, which causes infection. Clamping causes urine buildup. Elevating the bag above bladder level causes backflow. Disconnecting the closed system introduces bacteria.',
 true),

('cna','Activities of Daily Living',
 'A resident''s intake and output (I&O) is being recorded. Which item counts as fluid intake?',
 '["Scrambled eggs", "Gelatin (Jell-O) and ice cream", "Mashed potatoes", "Toast with butter"]',
 1,
 'Foods that are liquid at room temperature are counted as fluid intake on I&O records. Gelatin and ice cream melt to liquid. Solid foods like mashed potatoes, eggs, and toast do not count toward fluid intake.',
 true),

('cna','Activities of Daily Living',
 'When assisting a resident with oral care who has an altered level of consciousness, the nurse aide should:',
 '["Position the resident on their side with the head of bed at 30–45 degrees and use foam swabs moistened with water", "Perform oral care only once daily to reduce the risk of aspiration", "Brush teeth vigorously in all four quadrants", "Use a full cup of water to rinse the mouth"]',
 0,
 'Side-lying with slight head elevation allows fluid to drain out of the mouth rather than into the airway, reducing aspiration risk. Foam swabs with minimal moisture are used instead of a full toothbrush. Aspiration risk makes full water rinses dangerous.',
 true),

-- ── Basic Nursing Skills  +25 ─────────────────────────────────

('cna','Basic Nursing Skills',
 'A nurse aide is measuring a resident''s pulse. What is the normal adult pulse range?',
 '["50–90 beats per minute", "100–120 beats per minute", "40–60 beats per minute", "60–100 beats per minute"]',
 3,
 'The normal adult resting heart rate is 60–100 beats per minute. A pulse below 60 (bradycardia) or above 100 (tachycardia) should be reported to the nurse. Pulse is assessed at the radial artery for a full 60 seconds.',
 true),

('cna','Basic Nursing Skills',
 'What is the normal respiratory rate range for an adult at rest?',
 '["25–35 breaths per minute", "12–20 breaths per minute", "6–10 breaths per minute", "20–30 breaths per minute"]',
 1,
 'Normal adult respiratory rate at rest is 12–20 breaths per minute. Rates below 12 (bradypnea) or above 20 (tachypnea) are abnormal and must be reported. Respirations should be counted for a full 60 seconds without alerting the resident, as awareness can alter the rate.',
 true),

('cna','Basic Nursing Skills',
 'A resident''s oral temperature reads 101.2°F (38.4°C). This finding is:',
 '["Normal for an older adult", "Elevated (fever) and should be reported to the nurse", "Below normal (hypothermia) and should be reported", "Normal only if the resident recently had a hot beverage"]',
 1,
 'Normal oral temperature is approximately 97.6–99.6°F (36.4–37.6°C). A reading of 101.2°F indicates fever and must be reported to the nurse for assessment and potential treatment. Temperature is one of the most important early indicators of infection.',
 true),

('cna','Basic Nursing Skills',
 'When applying a sequential compression device (SCD) to a resident''s legs, the nurse aide should:',
 '["Apply them over open wounds or active DVT sites", "Remove them at night to give the legs a rest", "Wrap them as tightly as possible to maximize compression", "Apply them smoothly without wrinkles, ensure two fingers can be inserted under the device, and confirm the machine is plugged in and cycling"]',
 3,
 'SCDs prevent DVT by intermittently compressing the legs. Two fingers of clearance ensures they are snug but not compressive enough to impair circulation. Wrinkles cause pressure sores. SCDs are contraindicated over wounds or known DVT. They are typically worn continuously except during ambulation.',
 true),

('cna','Basic Nursing Skills',
 'The nurse aide observes a resident pulling at their IV tubing. What is the correct action?',
 '["Re-secure the tubing tightly around the resident''s arm", "Restrain the resident''s arm without consulting the nurse", "Remove the IV to prevent injury", "Gently redirect the resident''s hands and notify the nurse immediately"]',
 3,
 'Pulling at IV tubing can dislodge the catheter, cause infiltration, or result in bleeding. The nurse must be notified immediately to assess the site and determine next steps. Restraining without an order is inappropriate.',
 true),

('cna','Basic Nursing Skills',
 'Which is the correct technique for putting on sterile gloves?',
 '["Use bare hands to adjust both gloves after putting them on", "Touch both gloves on the outside palm surface to pull them on", "Blow into the gloves to open them before putting them on", "Touch only the inside (cuff) of the first glove with the bare hand; use the gloved hand to slide fingers under the cuff of the second glove"]',
 3,
 'Sterile gloving requires the bare hand to only contact the cuffed (inside) surface of the first glove. Once the first glove is on, the gloved hand slides under the folded cuff of the second glove (outside surface remains sterile). Touching the outside or adjusting with bare hands breaks sterile technique.',
 true),

('cna','Basic Nursing Skills',
 'When assisting a resident with ambulation using a standard cane, where should the cane be held?',
 '["Alternated between hands with each step", "On the stronger (unaffected) side", "In whichever hand feels more comfortable", "On the weaker (affected) side"]',
 1,
 'A cane is held on the stronger side to provide a wider base of support and reduce weight-bearing on the weaker side. The cane advances with the weaker leg, creating a stable tripod pattern.',
 true),

('cna','Basic Nursing Skills',
 'A nurse aide enters a room and finds a resident on the floor. What is the priority action?',
 '["Check for responsiveness and injury, call for help, and do not move the resident until the nurse arrives", "Ask the resident what happened before calling for help", "Immediately help the resident back into bed", "Leave the room to find a co-worker before assessing the resident"]',
 0,
 'Safety is the first priority. The aide assesses responsiveness and visible injury without moving the resident (movement could worsen a spinal or fracture injury), then calls for help. The nurse must assess before the resident is moved.',
 true),

('cna','Basic Nursing Skills',
 'A resident''s blood pressure reads 88/58 mmHg. Which additional finding most suggests the nurse aide should call for help urgently?',
 '["The resident ate a large meal 30 minutes ago", "The resident has a history of hypertension", "The resident is sleeping comfortably", "The resident is pale, diaphoretic, and says they feel faint"]',
 3,
 'Low blood pressure (88/58) combined with pallor, diaphoresis, and near-syncope indicates possible hemodynamic compromise or shock — an emergency. A sleeping resident with low BP may simply be at their baseline. History of hypertension and recent meals are contextual but do not indicate acute distress.',
 true),

('cna','Basic Nursing Skills',
 'The nurse aide is preparing to transfer a resident from bed to wheelchair. Before the transfer, the nurse aide should:',
 '["Place the wheelchair parallel to the bed, facing away", "Lock the wheelchair brakes and position the wheelchair at a 45-degree angle to the bed on the resident''s stronger side", "Position the footrests down during the transfer", "Leave the wheelchair brakes unlocked for easy repositioning"]',
 1,
 'Locking the brakes prevents the wheelchair from sliding during transfer. A 45-degree angle to the bed on the stronger side minimizes the pivot distance and weight on the weaker side. Footrests must be swung up out of the way to prevent tripping.',
 true),

('cna','Basic Nursing Skills',
 'Which action prevents the spread of C. difficile (C. diff)?',
 '["Use alcohol hand gel after glove removal", "Wash hands with soap and water — alcohol-based hand sanitizer is NOT effective against C. diff spores", "Implement droplet precautions", "Use standard precautions only"]',
 1,
 'C. difficile forms spores that are resistant to alcohol. Soap and water physically removes spores from hands. Contact precautions (gown and gloves) are required. Droplet precautions are not indicated for C. diff.',
 true),

('cna','Basic Nursing Skills',
 'When collecting a stool specimen, the nurse aide should:',
 '["Collect the specimen from the toilet bowl", "Mix the stool with toilet water before collecting", "Use a clean container and tongue blade, collect only a small sample avoiding toilet water, and deliver it to the lab promptly", "Wait until the end of the shift to deliver the specimen"]',
 2,
 'Stool specimens must be collected into a clean container using a tongue blade or provided scoop, avoiding toilet water contamination. Specimens are time-sensitive; prompt delivery ensures accurate results.',
 true),

('cna','Basic Nursing Skills',
 'When a resident is using an incentive spirometer, which instruction is correct?',
 '["Use the spirometer only once per day", "Breathe in and out rapidly to increase lung exercise", "Inhale slowly and deeply to raise the ball/piston as high as possible, hold for 2–3 seconds, then exhale", "Blow hard into the mouthpiece to raise the ball"]',
 2,
 'Incentive spirometers measure and encourage deep inhalation to expand alveoli and prevent atelectasis post-surgery or during bed rest. Slow deep inhalation, not exhalation or rapid breathing, is the correct technique. Frequency is typically every 1–2 hours while awake.',
 true),

('cna','Basic Nursing Skills',
 'A nurse aide observes a resident''s IV site is swollen, cool to the touch, and the resident reports pain at the site. These are signs of:',
 '["Phlebitis — inflammation of the vein", "Normal IV site appearance", "An allergic reaction to the IV medication", "Infiltration — the IV catheter has dislodged into surrounding tissue"]',
 3,
 'Swelling, coolness, and pain at an IV site indicate infiltration — fluid is leaking into subcutaneous tissue instead of the vein. The nurse must be notified immediately. Phlebitis presents with warmth and redness along the vein track. Allergic reaction would appear at a distance from the site.',
 true),

('cna','Basic Nursing Skills',
 'Which observation about a resident in a vest restraint must be reported immediately?',
 '["The restraint has a quick-release knot", "The resident can move their arms", "The restraint is tied to the bed frame with quick-release ties", "The resident''s lips are turning blue and they appear to be in respiratory distress"]',
 3,
 'Blue lips (cyanosis) and respiratory distress in a restrained resident may indicate the vest has ridden up and is constricting the chest or neck — a life-threatening emergency. Quick-release knots, arm movement, and frame ties are correct restraint practices.',
 true),

('cna','Basic Nursing Skills',
 'When emptying a urinary catheter drainage bag, the nurse aide should:',
 '["Touch the drain port to the container to prevent splashing", "Squeeze the bag to speed drainage", "Empty all residents'' catheter bags into the same measuring container", "Use a clean graduate (measuring cup) for each resident, avoid touching the drain port to the graduate, and record the output"]',
 3,
 'Each resident requires a dedicated measuring container to prevent cross-contamination. The drain port must not contact the container to maintain the closed drainage system and prevent infection. Squeezing can cause backflow.',
 true),

('cna','Basic Nursing Skills',
 'A nurse aide is working with a resident who has an airborne infection (tuberculosis). What PPE is required?',
 '["Gloves only", "An N95 respirator (fit-tested), gown, and gloves", "Gown and face shield only", "A standard surgical mask only"]',
 1,
 'Airborne precautions require an N95 respirator (or higher) because pathogens like TB are transmitted via tiny aerosolized particles that remain suspended in air. Standard surgical masks do not filter particles at this size. A negative-pressure room is also required.',
 true),

('cna','Basic Nursing Skills',
 'A nurse aide notices a co-worker skipping handwashing between residents. The best action is to:',
 '["Speak with the co-worker privately and, if the behavior continues, report it to the charge nurse", "Report the co-worker to administration immediately without speaking to them", "Say nothing to avoid conflict", "Do nothing because hand hygiene is the nurse''s responsibility"]',
 0,
 'Patient safety supersedes personal discomfort. The preferred approach is direct, respectful peer feedback first. If the behavior continues, the charge nurse or supervisor must be notified. Hand hygiene is everyone''s responsibility, not just nurses.',
 true),

('cna','Basic Nursing Skills',
 'When helping a resident walk with a walker, the nurse aide should instruct the resident to:',
 '["Walk with the walker even with the feet", "Advance the walker first, then step into it — do not carry the walker off the ground while walking", "Step beyond the walker with each stride", "Hold the walker at shoulder height"]',
 1,
 'The walker is advanced a short distance ahead, then the resident steps into it, keeping it flat on the floor. Carrying the walker eliminates its stability benefit. The walker handles should be at hip height (wrist level when standing).',
 true),

('cna','Basic Nursing Skills',
 'The nurse aide is applying a non-sterile wound dressing. Which action is correct?',
 '["Wipe across the wound repeatedly with the same gauze", "Apply the new dressing after cleaning, working from the center of the wound outward", "Blow on the wound to dry it before applying the dressing", "Reuse the inner packaging to hold the clean dressing temporarily"]',
 1,
 'Cleaning from center outward moves bacteria away from the wound. Wiping back and forth with the same gauze drags contamination into the wound. Blowing on wounds introduces oral bacteria. Inner packaging is not sterile once opened.',
 true),

('cna','Basic Nursing Skills',
 'A nurse aide is measuring blood pressure manually. In which artery is the pulse auscultated?',
 '["Femoral artery in the groin", "Radial artery at the wrist", "Carotid artery in the neck", "Brachial artery (in the antecubital space)"]',
 3,
 'Blood pressure is auscultated over the brachial artery in the antecubital fossa (bend of the elbow). The cuff is placed on the upper arm and the stethoscope bell or diaphragm is placed over the brachial artery.',
 true),

('cna','Basic Nursing Skills',
 'After a resident returns from having a procedure involving sedation, the nurse aide should prioritize:',
 '["Monitoring level of consciousness, vital signs, and reporting any unusual findings to the nurse", "Starting the resident''s physical therapy session", "Leaving the resident alone to rest quietly without monitoring", "Bringing the resident a full meal"]',
 0,
 'Sedation can cause respiratory depression, hypotension, and altered consciousness during recovery. Close monitoring of vital signs and neurological status is critical. Physical therapy and full meals are contraindicated immediately after sedation. The resident must not be left unmonitored.',
 true),

('cna','Basic Nursing Skills',
 'Which is an example of proper body mechanics for a nurse aide?',
 '["Reach over the side rail to reposition a resident without lowering the bed", "Twist the spine to pivot when transferring a resident", "Bend at the waist with legs straight when lifting", "Bend at the knees and hips, keep the back straight, and hold the load close to the body"]',
 3,
 'Proper body mechanics protect the nurse aide''s spine: bending at the knees (not the waist), maintaining a straight back, and keeping loads close to the body reduces spinal stress. Twisting and reaching from awkward positions are the leading causes of healthcare worker back injuries.',
 true),

('cna','Basic Nursing Skills',
 'What does "NPO" mean in a care plan?',
 '["No position orders", "Needs personal oxygen", "Nocturnal pulse oximetry monitoring", "Nothing by mouth — the resident should receive no food or fluids orally"]',
 3,
 'NPO (nil per os) is a Latin abbreviation meaning "nothing by mouth." A resident on NPO status must receive nothing orally — no food, water, ice chips, or oral medications — unless specifically ordered. NPO orders are common before surgery or diagnostic procedures.',
 true),

('cna','Basic Nursing Skills',
 'A resident on oxygen therapy via nasal cannula is confused and keeps removing the cannula. What should the nurse aide do?',
 '["Reapply the cannula calmly, redirect the resident, and notify the nurse of the behavior", "Remove the oxygen entirely since the resident doesn''t want it", "Strap the cannula to the resident''s face to keep it in place", "Increase the oxygen flow rate to make up for the time without oxygen"]',
 0,
 'The nurse must be informed because the resident''s oxygenation may be compromised and alternative delivery methods or safety interventions may be needed. Restraining with tape is inappropriate. Independently removing or adjusting oxygen requires a nurse''s directive.',
 true),

-- ── Psychosocial Care Skills  +7 ──────────────────────────────

('cna','Psychosocial Care Skills',
 'An elderly resident repeatedly says, "I just want to go home and see my family." The most therapeutic response by the nurse aide is:',
 '["Tell the resident their family doesn''t visit because they are busy", "Change the subject to distract the resident", "Remind the resident they cannot go home", "Sit with the resident, acknowledge their feelings, and listen empathetically"]',
 3,
 'Therapeutic communication involves acknowledging feelings and listening without judgment. Longing for home is common and reflects unmet emotional needs. Deflecting, dismissing, or reminding the resident of their situation without empathy is non-therapeutic and worsens distress.',
 true),

('cna','Psychosocial Care Skills',
 'A resident expresses anxiety about an upcoming medical procedure. What is the best response for the nurse aide?',
 '["Explain the medical details of the procedure", "Acknowledge the resident''s concern, listen, and inform the nurse so they can provide information or reassurance", "Tell the resident there is nothing to worry about", "Leave the resident alone to process the anxiety independently"]',
 1,
 'Acknowledging anxiety validates the resident''s experience. The nurse aide should listen supportively but cannot explain medical procedures — that is the nurse''s or provider''s responsibility. Dismissing anxiety ("nothing to worry about") is not therapeutic.',
 true),

('cna','Psychosocial Care Skills',
 'A resident with late-stage dementia becomes very calm when the nurse aide plays soft music from their era. This is an example of:',
 '["An ineffective approach because dementia cannot be treated with music", "Inappropriate use of entertainment instead of medical care", "A distraction technique that should not be used without a doctor''s order", "A non-pharmacological intervention that addresses psychosocial needs"]',
 3,
 'Music therapy and familiar sensory experiences are evidence-based non-pharmacological interventions for dementia-related agitation and anxiety. Familiarity can activate long-term memory and soothe emotional distress. No order is required for the aide to use this compassionate approach.',
 true),

('cna','Psychosocial Care Skills',
 'A resident who recently lost their spouse seems withdrawn and has decreased appetite. The nurse aide should:',
 '["Tell the resident they need to get over the loss and move on", "Force the resident to eat the full meal", "Avoid the topic of the spouse entirely to prevent upsetting the resident", "Spend extra time with the resident, encourage small amounts of food, and report the changes to the nurse"]',
 3,
 'Grief is a normal response to loss. Supportive presence, gentle encouragement, and monitoring for complications (weight loss, depression) are appropriate. The nurse must be informed of changes in behavior and appetite. Forcing food or dismissing grief is inappropriate.',
 true),

('cna','Psychosocial Care Skills',
 'A resident from a specific religious background declines a food item due to religious dietary laws. The nurse aide should:',
 '["Respect the refusal without question and report the preference to the nurse and dietary team", "Document the refusal without informing the nurse or dietary department", "Try to convince the resident to eat the item for nutritional reasons", "Tell the resident that dietary restrictions are not possible in a care facility"]',
 0,
 'Religious beliefs must be respected as part of the resident''s right to self-determination and dignity. The dietary team must be notified to provide compliant alternatives. Trying to override religious beliefs is disrespectful and violates resident rights.',
 true),

('cna','Psychosocial Care Skills',
 'A resident tells the nurse aide, "I''ve been thinking about my death a lot lately." The nurse aide should:',
 '["Change the subject to something positive", "Tell the resident not to think about death", "Assume the resident is just being dramatic", "Listen calmly, take the comment seriously, and report it to the nurse promptly"]',
 3,
 'Statements about death should always be taken seriously. While they may reflect normal reflection in older adults, they may also indicate depression or suicidal ideation. The nurse must be notified to assess the resident further. Dismissal or avoidance fails the resident.',
 true),

('cna','Psychosocial Care Skills',
 'When caring for a resident at the end of life, the nurse aide should:',
 '["Discuss prognosis and treatment options with the family", "Perform all procedures quickly to minimize the resident''s awareness", "Provide comfort care, speak softly, keep the environment calm, and honor the resident''s and family''s wishes", "Limit family visits to protect the resident''s energy"]',
 2,
 'End-of-life care focuses on comfort, dignity, and family support. A calm environment and respectful communication are essential. Family presence is encouraged, not limited. Discussing prognosis is the nurse''s and provider''s role, not the aide''s.',
 true),

-- ── Role of the Nurse Aide  +18 ───────────────────────────────

('cna','Role of the Nurse Aide',
 'A resident''s family member asks the nurse aide directly about the resident''s diagnosis and prognosis. What should the aide do?',
 '["Tell the family member the resident will be fine", "Tell the family member to search online", "Explain that medical information must come from the nurse or provider, and offer to connect them with the appropriate team member", "Share all available information to be helpful"]',
 2,
 'Nurse aides do not interpret medical information or share diagnoses with family members — this is outside their scope of practice and could violate HIPAA. The aide should redirect the family to the nurse or physician while remaining respectful and helpful.',
 true),

('cna','Role of the Nurse Aide',
 'Which behavior demonstrates professionalism for a nurse aide?',
 '["Discussing a resident''s personal information in the break room with friends", "Arriving on time, wearing a clean uniform, and maintaining confidentiality", "Leaving early when the shift is almost over", "Using personal cell phone to take photos of residents"]',
 1,
 'Professionalism includes punctuality, appropriate appearance, and protecting resident confidentiality. Discussing residents outside of care contexts, photographing them without consent, and abandoning a shift are violations of professional and legal standards.',
 true),

('cna','Role of the Nurse Aide',
 'When the nurse aide receives a new assignment they have not performed before, what should they do?',
 '["Attempt the task using best guesses", "Refuse the assignment without explanation", "Watch a video online and then proceed", "Inform the nurse that the task is outside their training and ask for instruction before proceeding"]',
 3,
 'Nurse aides must only perform tasks they are trained and competent to do. Informing the nurse of a gap in training ensures the resident receives safe, competent care and protects the aide from liability. Proceeding without training is dangerous.',
 true),

('cna','Role of the Nurse Aide',
 'What is the nurse aide''s responsibility when a resident''s condition changes unexpectedly?',
 '["Wait to see if the change resolves on its own", "Report the change at the end of the shift in the written notes", "Report the change to the nurse immediately and document the observation", "Try to determine the cause independently before reporting"]',
 2,
 'Any unexpected change in a resident''s condition (vital signs, mental status, behavior, physical appearance) requires immediate notification of the nurse. Early reporting allows timely intervention. Documentation follows notification but does not replace it.',
 true),

('cna','Role of the Nurse Aide',
 'A nurse aide witnesses a co-worker physically restraining a resident without an order and using excessive force. What is the correct action?',
 '["Intervene to stop the harm if safe to do so and report immediately to the supervisor", "Do nothing to avoid making things worse", "Assume there must be an order for the restraint", "Talk to the co-worker after the shift"]',
 0,
 'Physical abuse of a resident is a serious crime and must be stopped if safe to do so, then immediately reported to the supervisor. Nurse aides are mandatory reporters of abuse. Inaction or assumption of legitimacy makes the observer complicit.',
 true),

('cna','Role of the Nurse Aide',
 'Which action represents an appropriate professional boundary for a nurse aide?',
 '["Giving a resident your personal phone number in case they need help", "Accepting a large cash gift from a grateful resident''s family", "Becoming the resident''s personal friend and visiting on days off", "Providing warm, compassionate care without developing personal dependency with residents"]',
 3,
 'Professional boundaries maintain the therapeutic relationship while protecting both resident and aide. Accepting gifts of significant value, sharing personal contact information, and developing personal friendships cross professional boundaries and can create legal and ethical problems.',
 true),

('cna','Role of the Nurse Aide',
 'A nurse aide who disagrees with a care plan order should:',
 '["Express the concern through appropriate channels — speak with the charge nurse — and continue providing care as ordered unless it poses immediate harm", "Refuse to follow the order without discussion", "Change the care on their own without notifying anyone", "Complain to other aides but not to the nurse"]',
 0,
 'Care plans are developed by the licensed team. Concerns should be raised respectfully through proper channels. Care continues as ordered unless there is an immediate safety issue. Going around the chain of command or making unilateral changes disrupts team care and may harm the resident.',
 true),

('cna','Role of the Nurse Aide',
 'What is the correct response when a nurse aide makes a care error?',
 '["Report the error to the nurse immediately, document accurately, and cooperate with any incident report process", "Hide the error to avoid disciplinary action", "Ask a co-worker to cover for the error", "Wait to see if any harm occurs before reporting"]',
 0,
 'Transparency after errors is a professional and ethical obligation. Immediate reporting allows the nurse to intervene and prevent or minimize harm. Covering up errors delays treatment, increases harm, and creates serious legal liability.',
 true),

('cna','Role of the Nurse Aide',
 'A resident asks the nurse aide not to tell their roommate about a personal health matter. The nurse aide should:',
 '["Promise the resident complete confidentiality from everyone", "Assure the resident that personal health information will not be shared with the roommate, but explain that the care team needs to know for safe care", "Notify the family without the resident''s consent", "Tell the roommate anyway because residents share a room"]',
 1,
 'HIPAA protects residents'' health information from being shared with non-care team members, including other residents. The care team must be informed as needed for safe care. The roommate, family members, and visitors have no right to the resident''s health information.',
 true),

('cna','Role of the Nurse Aide',
 'What is the purpose of a minimum data set (MDS) in long-term care?',
 '["It is a standardized assessment tool used by the care team to plan and improve resident care", "It is a personal diary kept by the nurse aide", "It is a billing form for insurance companies only", "It is a list of rules for nurse aides to follow"]',
 0,
 'The MDS (Minimum Data Set) is a federally mandated, standardized comprehensive assessment for residents in Medicare/Medicaid-certified facilities. It informs care planning, determines reimbursement levels, and tracks resident outcomes over time. The nurse aide contributes observations to the MDS process.',
 true),

('cna','Role of the Nurse Aide',
 'A resident has an advance directive stating "Do Not Resuscitate" (DNR). The resident stops breathing. What should the nurse aide do?',
 '["Ignore the DNR because the resident may have changed their mind", "Call for the nurse immediately and stay with the resident — do not initiate CPR per the advance directive", "Leave the room to avoid involvement", "Begin CPR because it is always the right thing to do"]',
 1,
 'A DNR order must be honored. The nurse aide should call for the nurse immediately and stay with the resident for comfort care. Beginning CPR on a DNR resident violates their legal and ethical right to self-determination. The nurse will follow the directive and provide comfort measures.',
 true),

('cna','Role of the Nurse Aide',
 'A nurse aide notices a new bruise in a pattern that looks like fingers on a resident who appears fearful when a specific family member visits. What should the aide do?',
 '["Ask the family member directly if they caused the bruise", "Tell other residents about the concern", "Do not report it because the family member visits regularly", "Document the observation objectively, report it to the nurse and supervisor promptly, and treat it as suspected abuse"]',
 3,
 'Bruising in a pattern consistent with gripping, combined with fearfulness around a specific person, is a red flag for physical abuse. Nurse aides are mandatory reporters. Objective documentation and immediate reporting protect the resident. Confronting the suspect can escalate danger.',
 true),

('cna','Role of the Nurse Aide',
 'Which statement best describes the nurse aide''s role during a care conference?',
 '["Contribute direct-care observations about the resident''s daily functioning, behavior, and preferences", "Make independent clinical decisions about changes to the care plan", "Remain silent because only nurses and physicians may speak", "Diagnose problems and prescribe interventions"]',
 0,
 'The nurse aide provides the most direct, daily contact with the resident and contributes valuable observational data to the care conference — activity tolerance, mood, sleep patterns, appetite, and stated preferences. Their input shapes realistic, person-centered care plans.',
 true),

('cna','Role of the Nurse Aide',
 'Which action represents the correct use of a resident''s personal belongings?',
 '["Use items only as the resident directs or as specified in the care plan, and label all belongings to prevent loss", "Borrow the resident''s personal items with the intention of returning them", "Dispose of items that appear old or broken without asking", "Share the resident''s belongings with other residents who need them"]',
 0,
 'Residents have the right to keep and use their personal property. Borrowing, discarding, or sharing belongings without consent constitutes theft or misappropriation of property — a form of abuse reportable under state and federal law.',
 true),

('cna','Role of the Nurse Aide',
 'A nurse aide feels frustrated and overwhelmed during a busy shift. What is the appropriate response?',
 '["Leave the floor without notifying anyone", "Take frustration out on residents by rushing through care", "Take a brief moment to breathe, prioritize resident safety, and speak with the charge nurse if staffing or workload is unsafe", "Post complaints about coworkers on social media"]',
 2,
 'Compassionate care requires emotional regulation. Brief grounding techniques are appropriate. Unsafe staffing should be reported through proper channels. Rushing through care compromises safety. Abandoning the floor endangers residents. Social media complaints violate confidentiality and professionalism.',
 true),

('cna','Role of the Nurse Aide',
 'When accepting an assignment at the start of a shift, the nurse aide should:',
 '["Assume all residents'' needs are the same as the previous shift", "Begin care immediately without reviewing the assignment", "Refuse the assignment if any residents are unfamiliar", "Review the assignment, ask questions about unfamiliar residents or tasks, and note any special instructions before beginning care"]',
 3,
 'A thorough review at the start of the shift prevents errors. Asking questions before beginning care is professional and responsible. Resident conditions can change significantly between shifts. Assuming sameness from shift to shift is a safety risk.',
 true),

('cna','Role of the Nurse Aide',
 'A nurse aide should report which of the following observations to the nurse?',
 '["A resident who asks for a glass of water", "A resident with chronic obstructive pulmonary disease (COPD) whose breathing appears more labored than usual", "A resident who is sleeping during the afternoon", "A resident who ate 75% of their lunch"]',
 1,
 'Increased respiratory laboring in a COPD resident is a change from baseline and may indicate exacerbation, infection, or hypoxia — all requiring nurse assessment. The other observations are within expected normal parameters and do not require immediate reporting.',
 true),

('cna','Role of the Nurse Aide',
 'What is the nurse aide''s primary goal when providing care?',
 '["To complete tasks as efficiently as possible regardless of resident preferences", "To follow orders without questioning even when something seems wrong", "To support the resident''s safety, comfort, dignity, and independence to the greatest extent possible", "To make decisions about the resident''s care plan independently"]',
 2,
 'The foundation of person-centered care is supporting residents'' safety, comfort, dignity, and maximum independence. Efficiency matters but never supersedes individualized, dignified care. Questioning potential harm through appropriate channels is a professional responsibility.',
 true),

-- =============================================================
-- NCLEX RN  +70 questions  (subject_slug = 'rn')
-- =============================================================

INSERT INTO questions (subject_slug, domain, question_text, options, correct_index, explanation, active) VALUES

-- ── Safe & Effective Care  +22 ────────────────────────────────

('rn','Safe & Effective Care',
 'A nurse is planning care using Maslow''s hierarchy of needs. Which client need takes the highest priority?',
 '["A client requesting a phone call to family", "A client who is anxious about a diagnosis", "A client who is hypoxic with an SpO2 of 86%", "A client who states they feel unsafe in their room"]',
 2,
 'Maslow''s hierarchy places physiological needs (oxygen, circulation) at the top priority. An SpO2 of 86% represents life-threatening hypoxia — a physical emergency that supersedes safety, love/belonging, and esteem needs.',
 true),

('rn','Safe & Effective Care',
 'A nurse receives a telephone order from a provider. What is the correct action?',
 '["Refuse all telephone orders because they are not safe", "Write down the complete order, read it back to the provider for verification, and document as a telephone order with the provider''s name", "Wait until the provider arrives to write the order", "Accept the order verbally and implement it immediately without documentation"]',
 1,
 'Telephone orders must be written down immediately, read back completely to confirm accuracy, implemented, and documented with the time, provider name, and the nurse''s signature. Read-back is a Joint Commission requirement for all verbal/telephone orders.',
 true),

('rn','Safe & Effective Care',
 'A nurse is caring for a client who is a Jehovah''s Witness and refuses a blood transfusion despite life-threatening anemia. The nurse should:',
 '["Respect the client''s decision, document the refusal and the education provided, and notify the provider", "Administer the transfusion quickly before the client can object", "Override the refusal because the client''s life is at risk", "Call the client''s family to convince them to allow the transfusion"]',
 0,
 'A competent adult has the absolute legal and ethical right to refuse any medical treatment, including blood transfusions, based on religious or personal beliefs (autonomy). The nurse''s role is to ensure the client is informed, document the refusal, and notify the provider to explore alternatives.',
 true),

('rn','Safe & Effective Care',
 'The nurse is reviewing a new medication order: "Metoprolol 50 mg PO BID." Which part of the order requires clarification before administration?',
 '["The dose requires verification against normal range", "The route is missing", "No clarification needed — the order is complete", "The frequency BID (twice daily) is unsafe for beta-blockers"]',
 2,
 'The order is complete — it includes medication name, dose (50 mg), route (PO = oral), and frequency (BID = twice daily). 50 mg PO BID is within the standard therapeutic range for metoprolol. No clarification is required in this scenario.',
 true),

('rn','Safe & Effective Care',
 'Which nursing action best demonstrates application of the ethical principle of justice?',
 '["Providing the same quality of care to all clients regardless of their socioeconomic status or background", "Prioritizing care for clients who are more cooperative", "Performing a procedure on a client who has not consented", "Withholding information from a client to protect their feelings"]',
 0,
 'Justice in nursing ethics means fair, equitable distribution of care and resources without discrimination. All clients deserve the same standard of care regardless of income, race, religion, or behavior. The other options violate autonomy or beneficence.',
 true),

('rn','Safe & Effective Care',
 'A nurse identifies that a client received the wrong dose of a medication administered by the previous shift nurse. The error caused no apparent harm. The nurse should:',
 '["Tell the charge nurse but not the provider since the client seems fine", "Only document it in the chart but not complete an incident report", "Do nothing because no harm occurred", "Assess the client, notify the provider, complete an incident report, and document objectively in the medical record"]',
 3,
 'Medication errors require a full safety response regardless of whether harm is apparent: assess the client (harm may be delayed), notify the provider, complete a facility incident report (for quality improvement), and document factually in the chart. Incident reports are not placed in the chart.',
 true),

('rn','Safe & Effective Care',
 'A nurse is caring for a client who needs a central venous catheter. Which intervention is most important for preventing central line-associated bloodstream infection (CLABSI)?',
 '["Flush the line with tap water if sterile saline is unavailable", "Change the central line every 48 hours routinely", "Use maximal sterile barrier precautions during insertion and maintain a sterile dressing change protocol", "Apply antibacterial ointment to the insertion site at every dressing change"]',
 2,
 'Maximal sterile barrier precautions (full body drape, sterile gown and gloves, cap, mask) during insertion and strict aseptic technique during access and dressing changes are the most evidence-based CLABSI prevention strategies. Routine line changes increase infection risk. Tap water is never used. Routine antibiotic ointment is not recommended (promotes resistance).',
 true),

('rn','Safe & Effective Care',
 'A nurse is about to administer a high-alert medication (concentrated potassium chloride). Which safety action is required?',
 '["Administer as quickly as possible through an IV push", "Independent double-check with a second nurse before administration", "Skip the label check because the nurse drew up the medication themselves", "Mix with normal saline in a 500 mL bag without a pump"]',
 1,
 'High-alert medications such as concentrated electrolytes require an independent double-check by a second nurse to verify drug, dose, rate, and route before administration. Concentrated KCl must never be given as IV push — it causes cardiac arrest. It must be diluted and infused on a pump.',
 true),

('rn','Safe & Effective Care',
 'A nurse uses the Braden Scale. What is this assessment tool used for?',
 '["Screening for nutritional deficiency", "Assessing a client''s risk for developing pressure injuries", "Measuring a client''s risk of falling", "Evaluating pain intensity"]',
 1,
 'The Braden Scale assesses pressure injury risk by scoring six subscales: sensory perception, moisture, activity, mobility, nutrition, and friction/shear. Scores range from 6–23; lower scores indicate higher risk. The Morse Fall Scale assesses fall risk. Pain uses scales like NRS or FLACC.',
 true),

('rn','Safe & Effective Care',
 'Which statement about informed consent is correct?',
 '["Implied consent applies to all elective procedures", "Informed consent must be obtained by the provider performing the procedure, not the nurse", "The nurse can obtain surgical consent as long as the client asks questions", "Signed consent forms are only needed for surgical procedures"]',
 1,
 'It is the provider''s (surgeon''s, physician''s) legal responsibility to obtain informed consent by explaining the procedure, risks, benefits, and alternatives. The nurse''s role is to witness the signature and ensure the client understands — not to provide the medical disclosure.',
 true),

('rn','Safe & Effective Care',
 'A nurse is floating to an unfamiliar unit. Which assignment is safest for the float nurse to accept?',
 '["A client requiring complex wound vac management for the first time", "A stable postoperative client on their second day after an appendectomy", "A client in septic shock requiring vasopressor titration", "A newly admitted client with acute respiratory failure"]',
 1,
 'Float nurses should be assigned clients whose care most closely matches their training and competency. A stable postoperative client on day two has predictable, lower-complexity needs. Septic shock, complex wound vac management, and acute respiratory failure require unit-specific expertise.',
 true),

('rn','Safe & Effective Care',
 'When caring for a client under droplet precautions, the nurse should wear:',
 '["A surgical mask within 3 feet of the client", "Full body protective suit", "An N95 respirator at all times", "Gloves only — droplet precautions do not require a mask"]',
 0,
 'Droplet precautions (for influenza, pertussis, meningitis, etc.) require a surgical/procedure mask when within 3 feet of the client, in addition to standard precautions. N95 respirators are for airborne precautions (TB, measles, varicella). A private room or cohorting is also required.',
 true),

('rn','Safe & Effective Care',
 'A nurse''s client has a new order for physical therapy. The nurse should:',
 '["Assess the client''s current condition before PT arrives to ensure the order is still appropriate and safe", "Cancel the order if the client seems tired", "Administer a sedative first to help the client relax during PT", "Send the client to PT immediately without assessment"]',
 0,
 'Nursing assessment prior to therapy ensures the order is still safe and appropriate given the client''s current status (vital signs, pain level, recent changes). Nurses coordinate care and act as the client''s safety checkpoint before delegating to other disciplines.',
 true),

('rn','Safe & Effective Care',
 'A client states they want to leave the hospital against medical advice (AMA). The nurse''s priority action is:',
 '["Physically prevent the client from leaving", "Tell the client they will lose their insurance if they leave", "Call security immediately without first speaking with the client", "Inform the provider, ensure the client is mentally competent and understands the risks, have them sign the AMA form, and document thoroughly"]',
 3,
 'A competent adult has the right to leave AMA. The nurse''s role is to notify the provider, assess decision-making capacity, ensure the client understands the risks in clear language, offer alternatives, have them sign the AMA form (if willing), and document. Restraining or threatening a client is battery.',
 true),

('rn','Safe & Effective Care',
 'A nurse witnesses a sentinel event on the unit. What is a sentinel event?',
 '["A minor medication error with no harm", "A routine adverse drug reaction", "A near-miss event that was caught before reaching the patient", "An unexpected occurrence involving death or serious physical or psychological injury that is not related to the natural course of the patient''s illness"]',
 3,
 'The Joint Commission defines a sentinel event as an unexpected occurrence resulting in death, permanent harm, or temporary harm requiring life-sustaining intervention — not related to the natural course of illness. Sentinel events trigger a root cause analysis. Near-misses are close calls with no harm.',
 true),

('rn','Safe & Effective Care',
 'The nurse is caring for four clients. Which task is appropriate to delegate to a UAP?',
 '["Educating a client about a new insulin regimen", "Assessing the surgical wound of a client returned from the OR", "Ambulating a stable client who walked to the bathroom yesterday", "Interpreting a client''s oxygen saturation trend over the past hour"]',
 2,
 'Ambulation of a stable client who has demonstrated the ability to ambulate is within UAP scope. Assessment, education, and clinical interpretation are all nursing functions requiring licensure and clinical judgment and cannot be delegated to unlicensed personnel.',
 true),

('rn','Safe & Effective Care',
 'A nurse is preparing to restrain a client. Which statement about restraints is correct?',
 '["Restraints can be initiated by the nurse independently for any safety concern", "Restraints do not require physician orders in emergency situations", "Side rails always count as restraints", "A restraint requires a time-limited provider order, regular monitoring of circulation and skin, and documentation of less restrictive alternatives tried first"]',
 3,
 'Restraints require a provider order (time-limited per Joint Commission/CMS), documentation that less restrictive alternatives were attempted, and ongoing monitoring (every 15 minutes for violent/self-destructive restraints; every 2 hours for non-violent). All four side rails up may count as a restraint.',
 true),

('rn','Safe & Effective Care',
 'A nurse is caring for a client who does not speak English. To obtain informed consent, the nurse should:',
 '["Proceed without the interpreter if the client nods in agreement", "Ask the client''s family member to translate since they are present", "Use a bilingual nursing assistant to translate", "Use a trained medical interpreter — not a family member — to ensure accurate communication"]',
 3,
 'Trained medical interpreters are required for informed consent and significant health communications to ensure accuracy and protect the client''s rights. Family members may have conflicts of interest or lack medical vocabulary. Nodding without verbal comprehension is not valid consent.',
 true),

('rn','Safe & Effective Care',
 'The nurse receives a verbal order in an emergency. After implementing the order, the nurse should:',
 '["Leave documentation to the provider since they gave the order", "Document the verbal order per facility policy, including the provider name, date, time, and note that it was a verbal order in an emergency", "Only tell the charge nurse verbally; no written documentation is needed", "Document it at the next convenient time, which may be the next day"]',
 1,
 'Verbal orders in emergencies are acceptable but must be documented completely and promptly by the nurse receiving the order, including specifics of what was ordered, who ordered it, and timing. Provider co-signature is required within a facility-specified timeframe.',
 true),

('rn','Safe & Effective Care',
 'The nurse is teaching a new graduate about the "chain of command." This concept means:',
 '["Escalating a safety concern from the charge nurse, to the supervisor, to the medical director if lower levels do not respond", "Following physician orders without questioning them", "Only communicating concerns to the nurse manager", "Taking all complaints directly to the hospital administrator"]',
 0,
 'The chain of command is an escalation pathway for unresolved safety concerns. A nurse should first address the concern with the attending provider, then escalate to the charge nurse, nursing supervisor, department director, and beyond until the issue is resolved. This protects patient safety and is a professional obligation.',
 true),

('rn','Safe & Effective Care',
 'Which finding during medication reconciliation on admission requires immediate follow-up?',
 '["A client''s home medication list includes warfarin, but no INR has been ordered", "A client takes acetaminophen 500 mg PRN for headaches", "A client takes a daily multivitamin", "A client uses over-the-counter antacids occasionally"]',
 0,
 'Warfarin is a high-alert anticoagulant requiring ongoing INR monitoring to prevent bleeding or subtherapeutic dosing. Admitting a warfarin patient without ordering an INR is a safety gap requiring immediate follow-up. Vitamins, antacids, and low-dose acetaminophen are low-risk.',
 true),

('rn','Safe & Effective Care',
 'A nurse is caring for a client with a chest tube. Which finding requires immediate intervention?',
 '["Gentle, intermittent bubbling in the suction control chamber", "The water seal chamber level is at 2 cm H2O", "Drainage of 30 mL of serosanguineous fluid in 4 hours", "Tidaling (fluid moving with respirations) has stopped and there is no bubbling in the water seal chamber"]',
 3,
 'Cessation of tidaling in the water seal chamber suggests either lung re-expansion (expected after pneumothorax) OR a kinked, clamped, or obstructed tube — which must be ruled out immediately. Persistent bubbling in suction control and low serosanguineous drainage are normal. The 2 cm water seal level is standard.',
 true),

-- ── Physiological Integrity  +36 ──────────────────────────────

('rn','Physiological Integrity',
 'A nurse is caring for a client who takes NPH insulin at 7:00 AM. At which time should the nurse plan for the peak hypoglycemic effect?',
 '["11:00 AM – 3:00 PM (4–8 hours after administration)", "12:00 midnight (17 hours after administration)", "7:30 AM (30 minutes after administration)", "7:00 PM (12 hours after administration)"]',
 0,
 'NPH (intermediate-acting) insulin has an onset of 2–4 hours, peaks at 4–12 hours, and lasts 12–18 hours. After a 7:00 AM injection, the peak effect is between approximately 11 AM and 3 PM — the highest risk period for hypoglycemia. (Verified: NPH peak 4–12 hr, onset 2–4 hr — LevelUpRN/ATI pharmacology reference.)',
 true),

('rn','Physiological Integrity',
 'A client taking lithium for bipolar disorder has a serum lithium level of 1.8 mEq/L. The nurse should expect to:',
 '["Increase the lithium dose to reach a therapeutic level", "Hold the lithium, notify the provider, and monitor for signs of toxicity (coarse tremor, confusion, vomiting)", "Document the level as within the normal therapeutic range", "Administer the next dose as scheduled"]',
 1,
 'The therapeutic lithium range is 0.6–1.2 mEq/L. Levels above 1.5 mEq/L indicate toxicity. At 1.8 mEq/L, the client is experiencing moderate toxicity (coarse tremors, nausea, confusion, ataxia). The dose must be held and the provider notified immediately. (Source: StatPearls Lithium Toxicity; NCSBN pharmacology reference.)',
 true),

('rn','Physiological Integrity',
 'A nurse is preparing to mix regular insulin and NPH insulin in the same syringe. What is the correct technique?',
 '["Draw up regular (clear) insulin first, then NPH (cloudy) insulin — clear before cloudy", "Shake both vials vigorously to mix before drawing up", "Mix them in a separate vial before drawing up", "Draw up NPH first, then regular insulin"]',
 0,
 'The mnemonic "clear before cloudy" — regular (clear) insulin is always drawn up before NPH (cloudy) to prevent contaminating the regular vial with NPH, which would alter its onset. Long-acting insulins (glargine, detemir) should never be mixed. Vials are gently rolled, not shaken.',
 true),

('rn','Physiological Integrity',
 'A client is post-operative following abdominal surgery. On the second postoperative day, the client develops fever of 38.5°C (101.3°F). What is the most likely cause?',
 '["Wound infection", "Deep vein thrombosis", "Anastomotic leak", "Atelectasis — the most common cause of fever in the first 48–72 hours post-surgery"]',
 3,
 'Post-operative fever in the first 1–2 days is most commonly caused by atelectasis (collapsed alveoli from shallow breathing, secretion retention, and immobility). The mnemonic "Wind, Water, Wound, Walking, Wonder Drugs" helps sequence post-op fever causes chronologically — Wind (atelectasis) is first.',
 true),

('rn','Physiological Integrity',
 'A client has a serum potassium of 2.8 mEq/L. Which ECG change is the nurse most likely to observe?',
 '["Absent P waves and irregular rhythm", "Flattened T waves and presence of U waves", "Prolonged PR interval and shortened QT interval", "Peaked T waves and widened QRS complex"]',
 1,
 'Hypokalemia (K+ < 3.5 mEq/L) causes flattened T waves, prominent U waves (after T wave), ST depression, and widened QRS at severe levels. Peaked T waves and wide QRS suggest hyperkalemia. Absent P waves with irregular rhythm suggests atrial fibrillation. (Normal K+ 3.5–5.0 mEq/L — NCSBN reference.)',
 true),

('rn','Physiological Integrity',
 'A client with chronic kidney disease has a serum potassium of 6.2 mEq/L. Which intervention has the highest priority?',
 '["Schedule dialysis for the next available slot", "Prepare to administer sodium bicarbonate IV", "Place the client on a cardiac monitor", "Encourage increased fluid intake"]',
 2,
 'Hyperkalemia (K+ > 5.0 mEq/L) causes life-threatening cardiac dysrhythmias, including ventricular fibrillation. Cardiac monitoring is the priority to detect dysrhythmias while other interventions (kayexalate, insulin/glucose, calcium gluconate) are prepared. (K+ 6.2 mEq/L is severely elevated — NCSBN reference normal 3.5–5.0 mEq/L.)',
 true),

('rn','Physiological Integrity',
 'A nurse is assessing a client for signs of increased intracranial pressure (ICP). Which set of findings is most consistent with this condition?',
 '["Tachycardia, hypotension, and diaphoresis", "Agitation, confusion, and hyperthermia", "Decreasing level of consciousness, widening pulse pressure, and bradycardia (Cushing''s triad)", "Fever, nuchal rigidity, and photophobia"]',
 2,
 'Cushing''s triad — hypertension with widening pulse pressure, bradycardia, and irregular respirations — is a late, ominous sign of severely elevated ICP. Tachycardia with hypotension suggests shock. Fever, nuchal rigidity, and photophobia suggest meningitis. Agitation and hyperthermia suggest heat stroke or serotonin syndrome.',
 true),

('rn','Physiological Integrity',
 'A client who had a stroke is assessed using the NIH Stroke Scale. Which finding indicates the most severe impairment on this scale?',
 '["A score of 5 (minor stroke)", "A score of 25 (severe stroke)", "A score of 42 (catastrophic)", "A score of 1 (minimal deficit)"]',
 1,
 'The NIH Stroke Scale (NIHSS) ranges from 0 (no deficit) to 42 (most severe). Scores 21–42 represent severe strokes. A score of 25 indicates severe neurological impairment. Understanding this scale guides treatment urgency, thrombolytic eligibility, and prognosis.',
 true),

('rn','Physiological Integrity',
 'A client is having a generalized tonic-clonic seizure. What is the nurse''s priority action?',
 '["Insert a padded tongue blade to protect the airway", "Restrain the client''s extremities to prevent self-injury", "Leave the room to get help before doing anything else", "Protect the client from injury, turn onto the side if possible, and time the seizure — do not restrain or insert anything in the mouth"]',
 3,
 'During a seizure: protect from injury (pad side rails, remove hard objects), position on side if possible (prevents aspiration), time the seizure, and call for help. Never restrain (increases injury risk), never insert anything in the mouth (biting risk is a myth; objects cause trauma). Seizures >5 min are medical emergencies.',
 true),

('rn','Physiological Integrity',
 'A client with a myocardial infarction (MI) is receiving IV morphine. In addition to pain relief, what is the therapeutic goal of morphine in this context?',
 '["Stimulate coronary vasodilation directly", "Increase heart rate to improve cardiac output", "Replace nitroglycerin in the treatment protocol", "Reduce preload and afterload, thereby decreasing myocardial oxygen demand"]',
 3,
 'Morphine reduces venous preload (venodilation) and arterial afterload, decreasing the heart''s workload and oxygen demand — important in the setting of ischemia. It also reduces anxiety and sympathetic stimulation. Morphine does not increase heart rate or directly dilate coronary arteries.',
 true),

('rn','Physiological Integrity',
 'A nurse is caring for a client following a lumbar puncture. Which position should the client be maintained in?',
 '["Flat or low-Fowler''s position for 1–4 hours, with the head of bed no higher than 30 degrees", "High-Fowler''s position to prevent headache", "Prone position to reduce back pain", "Trendelenburg to prevent hypotension"]',
 0,
 'After lumbar puncture, clients are typically kept flat (or with minimal elevation up to 30 degrees per provider order) for 1–4 hours to equalize CSF pressure and reduce post-lumbar puncture headache (caused by CSF leaking from the puncture site). High-Fowler''s increases CSF pressure differential and worsens headache.',
 true),

('rn','Physiological Integrity',
 'A client with cirrhosis develops confusion, asterixis (hand flapping), and a serum ammonia of 118 mcg/dL. The nurse anticipates orders for:',
 '["IV albumin to correct coagulopathy", "Furosemide to reduce ascites", "Propranolol to prevent variceal bleeding", "Lactulose administration to reduce serum ammonia"]',
 3,
 'Elevated ammonia with confusion and asterixis indicates hepatic encephalopathy. Lactulose traps ammonia in the gut as ammonium ion, which is excreted in stool. It is the first-line treatment. Albumin, diuretics, and beta-blockers address other complications of cirrhosis but not acute encephalopathy.',
 true),

('rn','Physiological Integrity',
 'A nurse is assessing a client for compartment syndrome after a lower leg fracture. Which finding is the earliest and most sensitive indicator?',
 '["Pallor and paresthesias", "Pain disproportionate to the injury, especially with passive stretch of the muscles", "Paralysis of the affected limb", "Absent peripheral pulses"]',
 1,
 'The "6 Ps" of compartment syndrome are: Pain (earliest, most sensitive — especially with passive stretch), Pressure, Paresthesias, Paralysis, Pallor, and Pulselessness. Pain disproportionate to the injury and pain with passive stretch are the hallmark early findings. Absent pulses and paralysis are late, ominous signs.',
 true),

('rn','Physiological Integrity',
 'A client is prescribed warfarin. Which lab value is used to monitor therapeutic effectiveness?',
 '["aPTT — target 1.5–2.5× control", "INR (International Normalized Ratio), target 2.0–3.0 for most indications", "Fibrinogen level", "Platelet count"]',
 1,
 'Warfarin is monitored with the INR (derived from the PT). For most indications (DVT, PE, atrial fibrillation), the therapeutic INR is 2.0–3.0. Mechanical heart valves may require a higher target (2.5–3.5). aPTT monitors heparin therapy. (Therapeutic INR 2.0–3.0 — standard pharmacology reference.)',
 true),

('rn','Physiological Integrity',
 'A client develops signs of a pulmonary embolism. Which finding is the classic presentation?',
 '["Crushing substernal chest pain radiating to the left arm", "Productive cough with yellow sputum and low-grade fever", "Sudden onset pleuritic chest pain, dyspnea, and tachycardia", "Gradual onset of bilateral leg edema over several weeks"]',
 2,
 'Classic PE presentation: sudden-onset sharp (pleuritic) chest pain that worsens with breathing, dyspnea, tachycardia, and in large PEs, hypotension. Bilateral edema suggests heart failure or venous insufficiency. Productive cough with fever suggests pneumonia. Crushing chest pain is typical of MI.',
 true),

('rn','Physiological Integrity',
 'A client with a head injury has a Glascow Coma Scale (GCS) score of 7. How should the nurse interpret this?',
 '["Normal neurological function", "Moderate brain injury", "Severe brain injury — score ≤8 indicates coma", "Mild brain injury"]',
 2,
 'The Glasgow Coma Scale scores Eye opening (1–4), Verbal response (1–5), and Motor response (1–6), total 3–15. A score of 13–15 = mild injury; 9–12 = moderate; ≤8 = severe injury/coma (airway management is typically required). A score of 7 indicates coma.',
 true),

('rn','Physiological Integrity',
 'A nurse is preparing a client for a paracentesis. The client should be positioned:',
 '["Left lateral (Sims) position", "Supine with legs elevated", "Sitting upright or in high-Fowler''s position to allow ascites to pool in the lower abdomen", "Prone to access the peritoneum from the back"]',
 2,
 'Paracentesis removes peritoneal fluid (ascites) via needle insertion into the abdomen. Sitting upright allows fluid to pool in the lower abdomen by gravity, making needle access easier and reducing risk of puncturing bowel or vessels. The bladder must be emptied before the procedure.',
 true),

('rn','Physiological Integrity',
 'A client is receiving total parenteral nutrition (TPN) through a central line. The bag of TPN runs out before the replacement bag arrives. The nurse should:',
 '["Hang a 10% dextrose solution at the same rate to prevent rebound hypoglycemia", "Administer oral glucose supplements", "Flush the line with normal saline and leave it to hang until the bag arrives", "Clamp the central line and wait for the TPN bag"]',
 0,
 'Abruptly stopping TPN can cause rebound hypoglycemia because the exogenous glucose was suppressing endogenous insulin secretion. While awaiting the TPN bag, 10% dextrose at the same infusion rate prevents hypoglycemia. The line should not simply be clamped.',
 true),

('rn','Physiological Integrity',
 'A nurse is caring for a client in the immediate post-operative period following a thyroidectomy. Which assessment finding requires the most urgent intervention?',
 '["Hoarseness of voice", "A slight sore throat from intubation", "Stridor, respiratory distress, and tracheal deviation toward the operative side", "A small amount of serosanguineous drainage on the dressing"]',
 2,
 'Stridor and respiratory distress after thyroidectomy indicate tracheal compression from hematoma at the surgical site — a surgical emergency. The wound may need emergency opening. Sore throat and mild hoarseness are expected post-intubation and post-operative findings. Serosanguineous drainage is normal initially.',
 true),

('rn','Physiological Integrity',
 'A client with a burn injury over 40% of their body surface area is in the emergent phase. Which type of IV fluid is the priority?',
 '["Isotonic crystalloid solution such as 0.9% normal saline or lactated Ringer''s (Parkland formula)", "5% dextrose in water (D5W)", "Albumin solution", "Packed red blood cells"]',
 0,
 'The Parkland formula uses lactated Ringer''s (4 mL × body weight kg × % TBSA burned) to replace the massive fluid loss from capillary leak in the first 24 hours. Colloids (albumin) are generally deferred until after 24 hours. D5W is hypotonic and worsens edema. Blood is given for hemorrhagic shock, not burns.',
 true),

('rn','Physiological Integrity',
 'A client is recovering from an anterior wall myocardial infarction and develops a heart rate of 38 with hypotension. What is the priority intervention?',
 '["Apply supplemental oxygen and wait for spontaneous resolution", "Administer atropine IV per protocol and notify the provider", "Prepare for cardioversion", "Administer a beta-blocker to slow the rate further"]',
 1,
 'Symptomatic bradycardia (HR < 60 with hemodynamic compromise — hypotension, syncope, altered mental status) is treated first with IV atropine 0.5 mg. This is a recognized ACLS protocol. If atropine fails, transcutaneous pacing or dopamine/epinephrine infusion is next. Cardioversion treats tachyarrhythmias, not bradycardia.',
 true),

('rn','Physiological Integrity',
 'A nurse suspects a client is developing sepsis. According to the Sepsis-3 definition, which clinical criteria support this concern?',
 '["Heart rate > 90 and WBC > 12,000 alone", "Fever > 38.3°C alone", "Suspected infection with a SOFA score increase of ≥2 points", "Positive blood cultures with systolic BP < 90"]',
 2,
 'Sepsis-3 (2016) defines sepsis as life-threatening organ dysfunction (SOFA score ≥2) caused by a dysregulated response to infection. The older SIRS criteria (fever, tachycardia, high WBC) are no longer sufficient for diagnosis. Positive blood cultures are supportive but not required.',
 true),

('rn','Physiological Integrity',
 'A client is admitted with upper GI bleeding. Which clinical finding differentiates upper GI bleeding from lower GI bleeding?',
 '["Occult blood found only on stool guaiac testing", "Hematemesis (vomiting blood) or melena (black, tarry stools)", "Abdominal cramping without visible blood", "Bright red blood per rectum (hematochezia)"]',
 1,
 'Upper GI bleeding (from esophagus, stomach, duodenum) presents with hematemesis or melena (digested blood turns stools black and tarry). Lower GI bleeding typically presents with hematochezia (bright red blood per rectum). Occult blood is found in both; hematochezia usually indicates lower or very brisk upper source.',
 true),

('rn','Physiological Integrity',
 'A nurse is caring for a client in hypovolemic shock. Which assessment finding would the nurse expect to see early in the process?',
 '["Tachycardia with narrowing pulse pressure", "Decreased heart rate and warm flushed skin", "Hypertension with widening pulse pressure", "Bradycardia with bounding pulse"]',
 0,
 'Early (compensated) hypovolemic shock triggers the sympathetic response: tachycardia (to maintain cardiac output) and vasoconstriction (narrowing pulse pressure). Hypotension is a late sign. Bradycardia, bounding pulses, hypertension, and warm skin suggest distributive (septic/neurogenic) shock, not hypovolemic.',
 true),

('rn','Physiological Integrity',
 'A client is prescribed metformin for type 2 diabetes and is scheduled for a CT scan with contrast. What should the nurse do?',
 '["Switch the client to insulin permanently before the scan", "Hold metformin before and for 48 hours after the procedure per provider order — contrast can cause acute kidney injury, which increases metformin-induced lactic acidosis risk", "Administer metformin as usual since it does not interact with contrast dye", "Double the metformin dose before the scan"]',
 1,
 'IV contrast media can cause acute kidney injury. Impaired renal clearance of metformin can lead to dangerous lactic acidosis. Standard practice is to hold metformin at the time of the procedure and for 48 hours after, with renal function rechecked before resuming.',
 true),

('rn','Physiological Integrity',
 'A client has a wound with edges that have separated post-operatively, exposing the underlying fascia. This is called:',
 '["Evisceration", "Dehiscence", "Fistula formation", "Eschar formation"]',
 0,
 'Dehiscence is the partial or complete separation of wound edges. Evisceration is the protrusion of internal organs through the open wound (emergency: cover with moist sterile gauze, place the client supine with knees bent, call the surgeon). Eschar is dead tissue on a wound. A fistula is an abnormal passage between structures.',
 true),

('rn','Physiological Integrity',
 'A nurse is caring for a client with Addison''s disease who is experiencing an acute adrenal crisis. Which intervention is the priority?',
 '["Administer fludrocortisone only", "Administer IV hydrocortisone and aggressive IV fluid resuscitation", "Monitor blood glucose and give insulin if elevated", "Restrict fluids to prevent hypertension"]',
 1,
 'Acute adrenal crisis (Addisonian crisis) is life-threatening — caused by absence of cortisol and aldosterone. It presents with severe hypotension, hyponatremia, hyperkalemia, and hypoglycemia. IV hydrocortisone and aggressive isotonic fluid resuscitation are the immediate priorities. Fluid restriction would be fatal.',
 true),

('rn','Physiological Integrity',
 'A client with SIADH (syndrome of inappropriate antidiuretic hormone) has a serum sodium of 118 mEq/L with neurological symptoms. The nurse anticipates:',
 '["IV normal saline bolus at 1 L/hr", "Encouraging oral fluid intake to dilute the sodium concentration", "Furosemide administration to increase urine output", "Fluid restriction and possible hypertonic (3%) saline infusion for severe symptomatic hyponatremia"]',
 3,
 'SIADH causes dilutional hyponatremia (water retention, low Na). Severe symptomatic hyponatremia (Na < 120 with seizures, coma) requires cautious correction with fluid restriction and, in severe cases, hypertonic 3% saline. Correction must be slow (< 10–12 mEq/L per 24 hr) to prevent osmotic demyelination syndrome. (Normal Na 135–145 mEq/L — NCSBN reference.)',
 true),

('rn','Physiological Integrity',
 'A nurse is teaching a client about newly prescribed warfarin. Which statement indicates the client needs further teaching?',
 '["I need to get my INR checked regularly", "I should take a double dose tomorrow if I miss today''s dose", "I should avoid making major changes to my leafy green vegetable intake", "I should notify my dentist that I am on warfarin before any dental work"]',
 1,
 'Missing a dose of warfarin should never be compensated with a double dose — this dramatically increases bleeding risk. The correct instruction is to take the missed dose as soon as remembered on the same day, or skip it and resume the regular schedule the next day. All other statements reflect correct understanding.',
 true),

('rn','Physiological Integrity',
 'A client with chronic obstructive pulmonary disease (COPD) is being discharged with home oxygen. Which instruction is most important for safety?',
 '["Increase oxygen flow rate when feeling short of breath", "Use oxygen only during sleep", "Store oxygen tanks near the stove for easy access", "Keep oxygen at least 5 feet from open flames, and do not smoke or allow smoking in the home"]',
 3,
 'Oxygen is highly combustible and dramatically supports combustion. Home oxygen safety requires keeping tanks away from all heat sources, no smoking, and no open flames. The flow rate is prescribed and should not be self-adjusted. Oxygen use schedule is determined by the provider, not the patient.',
 true),

('rn','Physiological Integrity',
 'A client with chronic renal failure has a phosphorus level of 7.2 mg/dL. The nurse should expect an order for:',
 '["IV phosphorus replacement", "Increased dietary phosphorus intake", "A phosphorus-rich supplement", "Phosphate binders (e.g., calcium carbonate or sevelamer) to be taken with meals"]',
 3,
 'Hyperphosphatemia is common in chronic renal failure because the kidneys cannot excrete phosphorus. Phosphate binders taken with meals bind dietary phosphate in the gut before absorption. Dietary phosphorus restriction is also needed. IV phosphorus is for hypophosphatemia, the opposite condition.',
 true),

('rn','Physiological Integrity',
 'A nurse is caring for a client with acute pancreatitis. Which position provides the most comfort and reduces pain?',
 '["Prone position with a pillow under the abdomen", "High-Fowler''s with legs dangling off the bed", "Supine with legs flat", "Side-lying (fetal position) with knees drawn to chest, or sitting forward with trunk flexed"]',
 3,
 'Acute pancreatitis causes severe epigastric pain that radiates to the back. The fetal position or leaning forward reduces tension on the pancreatic capsule and retroperitoneal pressure, providing relief. Supine position extends the spine and worsens pain. NPO status is also maintained.',
 true),

('rn','Physiological Integrity',
 'A nurse is caring for a client with a nasogastric (NG) tube. Before administering an intermittent tube feeding, the nurse should first:',
 '["Verify tube placement by aspirating gastric contents and checking pH (≤5.5 confirms gastric placement), then assess residual volume", "Auscultate over the epigastrium while injecting air as the sole placement check", "Flush the tube with warm water and begin feeding immediately", "Position the client supine to ease infusion"]',
 0,
 'Before each feeding, tube placement must be confirmed. pH ≤ 5.5 of aspirated contents indicates gastric placement. Air auscultation alone is no longer considered reliable. Gastric residual volume is assessed to prevent aspiration. Head of bed must be elevated ≥ 30–45 degrees during feeding, not supine.',
 true),

('rn','Physiological Integrity',
 'A client develops a tension pneumothorax. Which clinical finding is unique to tension pneumothorax compared to simple pneumothorax?',
 '["Decreased oxygen saturation", "Tracheal deviation away from the affected side with severe hemodynamic compromise", "Chest pain and dyspnea", "Absent breath sounds on the affected side only"]',
 1,
 'Both simple and tension pneumothorax cause absent breath sounds on the affected side, chest pain, dyspnea, and decreased SpO2. Tension pneumothorax uniquely causes tracheal deviation away from the affected side (mediastinal shift) and rapid hemodynamic collapse from impaired venous return — a surgical emergency requiring immediate needle decompression.',
 true),

('rn','Physiological Integrity',
 'A nurse is managing a client''s epidural analgesia infusion. Which finding requires the nurse to stop the infusion and notify the provider immediately?',
 '["Blood pressure is 118/72 mmHg", "The client is unable to move their legs and reports numbness from the waist down", "The client reports mild itching", "Pain score decreased from 8 to 3"]',
 1,
 'Bilateral lower extremity motor paralysis and sensory loss with epidural analgesia may indicate epidural hematoma or excessive neural blockade — both requiring immediate intervention. Mild itching is a common opioid side effect managed conservatively. Pain relief and stable blood pressure are expected outcomes.',
 true),

-- ── Health Promotion  +6 ──────────────────────────────────────

('rn','Health Promotion',
 'A nurse is providing teaching on osteoporosis prevention to a postmenopausal client. Which recommendation is most evidence-based?',
 '["Calcium supplementation alone is sufficient", "A low-impact sedentary lifestyle to prevent falls", "Adequate calcium (1,200 mg/day), vitamin D (800–1,000 IU/day), and weight-bearing exercise", "Hormone replacement therapy is the first-line prevention for all postmenopausal women"]',
 2,
 'Osteoporosis prevention in postmenopausal women requires calcium 1,200 mg/day, vitamin D 800–1,000 IU/day, and regular weight-bearing exercise (walking, resistance training), which stimulates bone remodeling. HRT carries risks and is not universally recommended. Calcium alone is insufficient. (Source: National Osteoporosis Foundation guidelines.)',
 true),

('rn','Health Promotion',
 'A nurse is counseling a client about smoking cessation using the "5 A''s" framework. What does the second "A" (Advise) involve?',
 '["Helping the client set a quit date and plan", "Arranging follow-up and referrals", "Giving clear, strong, personalized advice to quit smoking", "Asking if the client smokes"]',
 2,
 'The 5 A''s of smoking cessation: Ask (screen for tobacco use), Advise (give strong, clear, personalized advice to quit), Assess (willingness to make a quit attempt), Assist (help with a quit plan, medications), Arrange (follow-up). The Advise step is distinct from asking — it is the intervention itself.',
 true),

('rn','Health Promotion',
 'A client asks the nurse when they should start receiving annual mammograms. Based on current guidelines (American Cancer Society 2023), the nurse should say:',
 '["Women with average risk should have the opportunity to start annual screening at age 40, with annual screenings strongly recommended beginning at age 45", "All women should begin mammograms at age 30", "Mammograms are only needed if there is a family history of breast cancer", "Mammograms are not recommended until age 65"]',
 0,
 'The American Cancer Society recommends that average-risk women may begin annual mammograms at 40 (with the choice), and should begin annual screening at 45, transitioning to every 2 years at 55 if preferred. High-risk women may begin earlier with MRI. Family history, genetic mutations, and prior radiation lower the starting age.',
 true),

('rn','Health Promotion',
 'A nurse is teaching a client about the hepatitis B vaccine. Which client requires the vaccine most urgently?',
 '["A 28-year-old healthcare worker who has never been vaccinated", "A 5-year-old who received the complete series as an infant", "An adult who has documented immunity from prior infection", "A 65-year-old who completed the three-dose series 10 years ago"]',
 0,
 'Healthcare workers are at significant occupational risk for bloodborne pathogen exposure. An unvaccinated healthcare worker requires immediate hepatitis B vaccination. Those with completed series, childhood vaccination, or documented immunity (anti-HBs positive) do not need re-vaccination.',
 true),

('rn','Health Promotion',
 'A client asks about the purpose of the AUDIT-C screening tool. The nurse correctly explains that it is used to:',
 '["Diagnose alcohol-induced liver disease", "Measure blood alcohol content", "Screen for alcohol use disorder and identify hazardous drinking patterns", "Screen for illicit drug use"]',
 2,
 'The AUDIT-C (Alcohol Use Disorders Identification Test — Consumption) is a validated three-question screening tool for hazardous alcohol use and alcohol use disorder. It does not measure BAC, screen for other substances, or diagnose organ damage.',
 true),

('rn','Health Promotion',
 'A nurse is teaching a client with hypertension about lifestyle modifications. Which modification has the greatest evidence for blood pressure reduction?',
 '["Following a DASH diet combined with sodium restriction to less than 2,300 mg per day", "Avoiding all physical activity to reduce cardiovascular stress", "Increasing caffeine intake to improve cardiac output", "Consuming a high-protein diet"]',
 0,
 'The DASH diet (rich in fruits, vegetables, whole grains, low-fat dairy, lean proteins) combined with sodium restriction to < 2,300 mg/day (ideally < 1,500 mg in hypertension) can reduce systolic BP by 8–14 mmHg — comparable to a single antihypertensive medication. Regular aerobic exercise adds further benefit.',
 true),

-- ── Psychosocial Integrity  +7 ────────────────────────────────

('rn','Psychosocial Integrity',
 'A nurse is caring for a client with schizophrenia who states, "The TV is sending me special messages." The nurse recognizes this as:',
 '["Flight of ideas", "A hallucination", "An idea of reference — a type of delusional thinking", "Tangentiality"]',
 2,
 'An idea of reference is the belief that neutral events (a TV broadcast, a song) have special personal significance directed at the individual — a form of delusional thinking common in schizophrenia. A hallucination is a sensory perception without external stimulus. Flight of ideas is rapid, loosely connected thought. Tangentiality is moving away from the point of conversation.',
 true),

('rn','Psychosocial Integrity',
 'A nurse is using therapeutic communication. Which response is an example of reflection?',
 '["\"Don''t worry, everything will be fine\"", "\"Why do you feel that way?\"", "\"It sounds like you''re feeling frightened about the surgery\"", "\"Let me tell you about other patients who have had this surgery\""]',
 2,
 'Reflection mirrors back the client''s expressed feelings to show understanding and encourage further exploration. "It sounds like you''re feeling frightened" restates the emotional content the client implied. "Don''t worry" offers false reassurance. "Why" questions can feel accusatory. Sharing other patients'' experiences redirects away from the client.',
 true),

('rn','Psychosocial Integrity',
 'A client is being treated for anorexia nervosa. Which nursing intervention is the priority during the refeeding phase?',
 '["Encourage large, calorically dense meals immediately to restore weight quickly", "Restrict the client to bed rest to prevent caloric expenditure", "Monitor electrolytes closely, especially phosphate, and cardiac rhythm for refeeding syndrome", "Weigh the client after each meal"]',
 2,
 'Refeeding syndrome is a potentially fatal complication of reintroducing nutrition after prolonged starvation. Rapid cellular uptake of phosphate, potassium, and magnesium causes life-threatening electrolyte shifts and cardiac dysrhythmias. Electrolyte monitoring and a gradual refeeding protocol are essential.',
 true),

('rn','Psychosocial Integrity',
 'A nurse is caring for a client experiencing acute grief after the death of a spouse. The client says, "If only I had made him go to the doctor sooner." This statement reflects which stage of Kübler-Ross\'s grief model?',
 '["Bargaining","Denial","Anger","Depression"]',
 0,
 'Bargaining is characterized by "if only" and "what if" thoughts — attempts to regain control or undo the loss retroactively. Denial is the refusal to accept reality. Anger may be directed at self, others, or the deceased. Depression involves profound sadness and withdrawal. Kübler-Ross stages do not occur in a fixed sequence.',
 true),

('rn','Psychosocial Integrity',
 'A nurse is assessing a client for post-traumatic stress disorder (PTSD). Which cluster of symptoms is most characteristic?',
 '["Paranoid ideation and disorganized speech", "Recurring obsessions and compulsions that interfere with daily functioning", "Re-experiencing the trauma (flashbacks, nightmares), avoidance, negative mood changes, and hyperarousal", "Persistent sadness, anhedonia, and weight loss over two weeks"]',
 2,
 'PTSD (DSM-5) is characterized by four symptom clusters: intrusion (flashbacks, nightmares), avoidance (of trauma-related stimuli), negative cognitions/mood, and hyperarousal (startle response, sleep disturbance, irritability). Persistent sadness with anhedonia is MDD. Obsessions/compulsions are OCD. Paranoid ideation with disorganized speech is schizophrenia.',
 true),

('rn','Psychosocial Integrity',
 'A client with bipolar I disorder is in a manic episode. Which nursing action is the priority?',
 '["Ensure the client\'s safety and basic physiological needs are met by providing a structured, low-stimulation environment","Engage the client in detailed group activities to channel their energy","Encourage the client to express their thoughts freely without any redirection","Provide a highly stimulating environment to match the client\'s energy level"]',
 0,
 'During mania, clients have impaired judgment, decreased need for sleep, and hyperactivity — all creating safety risks (falls, impulsive dangerous decisions, dehydration, exhaustion). Safety and meeting basic needs (hydration, nutrition, sleep) are the priority. Low stimulation reduces escalation. Group activities and high stimulation worsen mania.',
 true),
('rn','Psychosocial Integrity',
 'A nurse applies the principle of the least restrictive intervention when caring for an agitated client. Which sequence correctly follows this principle?',
 '["Physical restraint → medication → verbal de-escalation", "Immediate pharmacological sedation, then verbal de-escalation", "Verbal de-escalation → environmental modifications → pharmacological intervention → physical restraint as last resort", "Physical restraint first to ensure safety, then verbal de-escalation"]',
 2,
 'The least restrictive principle requires using the minimum intervention necessary to ensure safety. Verbal de-escalation (calm presence, clear communication, offering choices) is always the first approach. Environmental adjustments (reducing stimulation, offering privacy) come next. Medications are used when verbal measures fail. Physical restraints require a provider order and are an absolute last resort with ongoing monitoring and documentation.',
 true);
